BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `Teacher` (
	`Id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`FirstName`	TEXT NOT NULL,
	`LastName`	TEXT NOT NULL,
	`Birthdate`	TEXT NOT NULL
);
INSERT INTO `Teacher` VALUES (1,'max','yudin','27.08.1985');
INSERT INTO `Teacher` VALUES (2,'elena','yudina','10.03.1986');
CREATE TABLE IF NOT EXISTS `Student` (
	`Id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`CreateDate`	TEXT NOT NULL,
	`FirstName`	TEXT NOT NULL,
	`SecondName`	TEXT NOT NULL,
	`LastName`	TEXT,
	`BirthDate`	TEXT NOT NULL,
	`Comment`	TEXT
);
COMMIT;
